export {default as Navbar}from './Navbar/Navbar'
export {default as Sell}from './Sell/Sell'
export {default as Footer}from './Footer/Footer'
export {default as Technology}from './Technology/Technology'
export {default as Businesses}from './Businesses/Businesses'